version: 2.1
orbs:
  elixir: coletiv/elixir@0.1.2
# executors:
#   default:
#     docker:
#       - image: circleci/elixir:1.9.4
#         environment:
#           MIX_ENV: test
jobs:
  test:
    executor:
      name: elixir/default
      elixir-version: 1.9.4
    steps:
      - elixir/build
      - elixir/check-format
      - elixir/test
workflows:
  build:
    jobs:
      - test
