version: 2.1
orbs:
  elixir: coletiv/elixir@0.1.2
jobs:
  test:
    executor:
      name: elixir/default
      elixir-version: 1.9.4
    steps:
      - elixir/build
      - elixir/check-format
      - elixir/dialyzer
      - elixir/test
workflows:
  build:
    jobs:
      - test
